name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - 'BE/**'
      - 'snowflake-embedding/**'
      - '.github/workflows/docker-image.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
 

    strategy:
      matrix:
        context:
          - path: BE
            image: us.icr.io/itz-watson-apps-gw7e10of-cr/fish-image-classify:latest
          - path: snowflake-embedding
            image: us.icr.io/itz-watson-apps-gw7e10of-cr/snowflake-embedding-image:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to IBM Cloud Container Registry
        run: |
          echo "${{ secrets.ICR_PASSWORD }}" | docker login -u "${{ secrets.ICR_USERNAME }}" --password-stdin "${{ secrets.ICR_REGION }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.context.image }} ${{ matrix.context.path }}

      - name: Push Docker image
        run: |
          docker push ${{ matrix.context.image }}
